"""
Sample NBA games for the GameNight MVP.

Factor scores are on a 0–100 scale. Watch Score and why_watch are computed
at request time by scoring.py — they are not stored here.
"""

from datetime import datetime

# Realistic tonight's slate — times are Eastern for display purposes.
SAMPLE_GAMES: list[dict] = [
    {
        "id": "nba-2026-06-15-lal-bos",
        "league": "NBA",
        "home_team": "Boston Celtics",
        "away_team": "Los Angeles Lakers",
        "start_time": datetime(2026, 6, 15, 20, 0, 0),
        "network": "ESPN",
        "offense_score": 88,
        "defense_score": 82,
        "star_power_score": 95,
        "close_game_score": 78,
        "rivalry_score": 92,
        "playoff_importance_score": 85,
        "accessibility_score": 90,
    },
    {
        "id": "nba-2026-06-15-den-min",
        "league": "NBA",
        "home_team": "Minnesota Timberwolves",
        "away_team": "Denver Nuggets",
        "start_time": datetime(2026, 6, 15, 19, 30, 0),
        "network": "TNT",
        "offense_score": 84,
        "defense_score": 79,
        "star_power_score": 90,
        "close_game_score": 85,
        "rivalry_score": 70,
        "playoff_importance_score": 88,
        "accessibility_score": 85,
    },
    {
        "id": "nba-2026-06-15-gsw-phx",
        "league": "NBA",
        "home_team": "Phoenix Suns",
        "away_team": "Golden State Warriors",
        "start_time": datetime(2026, 6, 15, 22, 0, 0),
        "network": "ESPN",
        "offense_score": 86,
        "defense_score": 72,
        "star_power_score": 88,
        "close_game_score": 80,
        "rivalry_score": 75,
        "playoff_importance_score": 80,
        "accessibility_score": 90,
    },
    {
        "id": "nba-2026-06-15-mil-phi",
        "league": "NBA",
        "home_team": "Philadelphia 76ers",
        "away_team": "Milwaukee Bucks",
        "start_time": datetime(2026, 6, 15, 19, 0, 0),
        "network": "NBA TV",
        "offense_score": 82,
        "defense_score": 78,
        "star_power_score": 85,
        "close_game_score": 82,
        "rivalry_score": 68,
        "playoff_importance_score": 86,
        "accessibility_score": 60,
    },
    {
        "id": "nba-2026-06-15-nyk-mia",
        "league": "NBA",
        "home_team": "Miami Heat",
        "away_team": "New York Knicks",
        "start_time": datetime(2026, 6, 15, 20, 30, 0),
        "network": "TNT",
        "offense_score": 75,
        "defense_score": 80,
        "star_power_score": 72,
        "close_game_score": 88,
        "rivalry_score": 82,
        "playoff_importance_score": 78,
        "accessibility_score": 85,
    },
    {
        "id": "nba-2026-06-15-dal-mem",
        "league": "NBA",
        "home_team": "Memphis Grizzlies",
        "away_team": "Dallas Mavericks",
        "start_time": datetime(2026, 6, 15, 20, 0, 0),
        "network": "ESPN",
        "offense_score": 80,
        "defense_score": 76,
        "star_power_score": 82,
        "close_game_score": 75,
        "rivalry_score": 55,
        "playoff_importance_score": 72,
        "accessibility_score": 90,
    },
    {
        "id": "nba-2026-06-15-sac-por",
        "league": "NBA",
        "home_team": "Portland Trail Blazers",
        "away_team": "Sacramento Kings",
        "start_time": datetime(2026, 6, 15, 22, 0, 0),
        "network": "NBA TV",
        "offense_score": 78,
        "defense_score": 65,
        "star_power_score": 70,
        "close_game_score": 72,
        "rivalry_score": 45,
        "playoff_importance_score": 55,
        "accessibility_score": 55,
    },
    {
        "id": "nba-2026-06-15-cle-ind",
        "league": "NBA",
        "home_team": "Indiana Pacers",
        "away_team": "Cleveland Cavaliers",
        "start_time": datetime(2026, 6, 15, 19, 0, 0),
        "network": "League Pass",
        "offense_score": 74,
        "defense_score": 77,
        "star_power_score": 68,
        "close_game_score": 70,
        "rivalry_score": 60,
        "playoff_importance_score": 65,
        "accessibility_score": 35,
    },
]
